<?php


use App\Database\{PDODatabaseConnection, PDOQueryBuilder};
use App\Exceptions\{ConfigFileNotValidException, PdoDatabaseException};
use App\Helpers\{Config, HttpClient};
use GuzzleHttp\Client;
use GuzzleHttp\Exception\GuzzleException;
use PHPUnit\Framework\TestCase;

class CrudTest extends TestCase
{
    private PDOQueryBuilder $queryBuilder;
    private $httpClient;

    /**
     * @throws GuzzleException
     */
    public function testItCanCreateDataWithApi(): mixed
    {
        $data = [
            'json' => [
                'title' => 'DWSr',
                'href' => 'https://api.com',
                'user' => 'DHmV',
                'email' => 'api.mr.basirnia@gmail.com'
            ]
        ];

        $response = $this->httpClient->post('index.php', $data);

        $this->assertEquals(200, $response->getStatusCode());

        $result = $this->queryBuilder
            ->table('bugs')
            ->where('title', 'DWSr')
            ->where('user', 'DHmV')
            ->first();

        $this->assertNotNull($result);

        return $result;
    }

    /**
     * check update with api is successfully
     *
     * @param $data
     * @depends testItCanCreateDataWithApi
     *
     * @return void
     * @throws GuzzleException
     */
    public function testItCanUpdateWithApi($data): void
    {
        $update = [
            'json' => [
                'id' => $data['id'],
                'title' => 'update with api'
            ]
        ];

        $response = $this->httpClient->put('index.php', $update);

        $this->assertEquals(200, $response->getStatusCode());

        $record = $this->queryBuilder->table('bugs')->find($data['id']);

        $this->assertNotNull($record);
        $this->assertEquals('update with api', $record['title']);
    }

    /**
     * get request for fetch data
     *
     * @depends testItCanCreateDataWithApi
     * @param array $data
     * @return void
     */
    public function testItCanFetchDataWithApi(array $data): void
    {
        $response = $this->httpClient->get('index.php', [
            'json' => [
                'id' => $data['id']
            ]
        ]);

        $this->assertEquals(200, $response->getStatusCode());
        $this->assertArrayHasKey('id', json_decode($response->getBody(), true));
    }

    /**
     * @throws ConfigFileNotValidException|PdoDatabaseException
     */
    protected function setUp(): void
    {
        $pdo = new PDODatabaseConnection($this->config());
        $this->queryBuilder = new PDOQueryBuilder($pdo->connect());

        $this->httpClient = new HttpClient();

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    private function config()
    {
        return Config::get('database', 'pdo_testing');
    }

    protected function tearDown(): void
    {
        $this->httpClient = null;

        parent::tearDown();
    }
}
