<?php


use App\Database\{PDODatabaseConnection, PDOQueryBuilder};
use App\Exceptions\{ConfigFileNotValidException, PdoDatabaseException};
use App\Helpers\{Config, HttpClient};
use GuzzleHttp\Exception\GuzzleException;
use PHPUnit\Framework\TestCase;

class CrudTest extends TestCase
{
    private PDOQueryBuilder $queryBuilder;
    private $httpClient;

    /**
     * @throws GuzzleException
     */
    public function testItCanCreateDataWithApi(): void
    {
        $data = [
            'json' => [
                'title' => 'DWSr',
                'href' => 'https://api.com',
                'user' => 'DHmV',
                'email' => 'api.mr.basirnia@gmail.com'
            ]
        ];

        $response = $this->httpClient->post('index.php', $data);

        $this->assertEquals(200, $response->getStatusCode());

        $result = $this->queryBuilder
            ->table('bugs')
            ->where('title', 'DWSr')
            ->where('user', 'DHmV')
            ->first();

        $this->assertNotNull($result);
    }

    /**
     * @throws ConfigFileNotValidException|PdoDatabaseException
     */
    protected function setUp(): void
    {
        $pdo = new PDODatabaseConnection($this->config());
        $this->queryBuilder = new PDOQueryBuilder($pdo->connect());

        $this->httpClient = new HttpClient();

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    private function config()
    {
        return Config::get('database', 'pdo_testing');
    }

    protected function tearDown(): void
    {
        $this->httpClient = null;

        parent::tearDown();
    }

}
